### ISSUE TITLE
Issue with cluster name

### ISSUE THREAD

**Issue by docbyte86** [stackitcloud/terraform-provider-stackit#223] opened 2024-01-22 07:55 UTC
Provider version 0.9.0

Error:

│ Error: Error creating/updating cluster
│ 
│   with module.ske.stackit_ske_cluster.ske,
│   on .terraform/modules/ske/main.tf line 5, in resource "stackit_ske_cluster" "ske":
│    5: resource "stackit_ske_cluster" "ske" {
│ 
│ Calling API: 400 Bad Request, status code 400, Body:
│ {"code":"InvalidArgument","message":"invalid input: cluster with name
│ \"b31b5fe4-s\"","details":""}

Plan:

      + name                    = "b31b5fe4-s"

It is working with portal, manually:

![image](https://github.com/stackitcloud/terraform-provider-stackit/assets/42868184/934e9e8e-d750-40fb-930c-e3f6954700d2)

**Comment by hcsa73** [comment] 2024-01-22 11:14
Hello, thanks for opening the issue!

The error is coming from the API. It simply says there's something wrong with the cluster `b31b5fe4-s`, not necessarily that the name is invalid (which it isn't, as you've checked). Unfortunately it doesn't offer any other details, so I can't tell what the problem is.

Could you share the cluster's plan that is stated on the .tf files, and how exactly this happened (were you creating a cluster, updating an existing one...)?

**Comment by docbyte86** [comment] 2024-01-22 11:50
We want to create a new cluster.
Please find the plan output, below:

```

Terraform will perform the following actions:

  # module.ske.stackit_ske_cluster.ske will be created
  + resource "stackit_ske_cluster" "ske" {
      + extensions              = {
          + acl   = {
              + allowed_cidrs = [
                  + "0.0.0.0/0",
                ]
              + enabled       = true
            }
          + argus = {
              + argus_instance_id = "79668603-adc7-4fb3-ab8e-1ceec7b89a17"
              + enabled           = true
            }
        }
      + hibernations            = []
      + id                      = (known after apply)
      + kube_config             = (sensitive value)
      + kubernetes_version      = "1.26"
      + kubernetes_version_used = (known after apply)
      + maintenance             = {
          + enable_kubernetes_version_updates    = true
          + enable_machine_image_version_updates = true
          + end                                  = "02:23:45Z"
          + start                                = "01:23:45Z"
        }
      + name                    = "tobi-sbx"
      + node_pools              = [
          + {
              + availability_zones = [
                  + "eu01-3",
                ]
              + cri                = "containerd"
              + labels             = {
                  + "pool"  = "pool-1"
                  + "stage" = "sbx"
                }
              + machine_type       = "c1.3"
              + max_surge          = 1
              + max_unavailable    = 1
              + maximum            = 4
              + minimum            = 2
              + name               = "groot-sbx01"
              + os_name            = "flatcar"
              + os_version         = "3602.2.1"
              + volume_size        = 20
              + volume_type        = "storage_premium_perf1"
            },
        ]
      + project_id              = "7199c212-5324-4877-a0f3-c935e91f30c2"
    }

  # module.vault.vault_kv_secret_v2.vault will be created
  + resource "vault_kv_secret_v2" "vault" {
      + data                = (sensitive value)
      + data_json           = (sensitive value)
      + delete_all_versions = false
      + disable_read        = false
      + id                  = (known after apply)
      + metadata            = (known after apply)
      + mount               = "a84d701e-1f82-46e9-b905-f145d8124c38"
      + name                = "terraform"
      + path                = (known after apply)

      + custom_metadata {
          + max_versions = 3
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + kube_config             = (sensitive value)
  + kubernetes_version_used = (known after apply)
```

**Comment by hcsa73** [comment] 2024-01-22 14:36
Could you try changing the nodepool's OS version (`stackit_ske_cluster.node_pools[0].os_version`) to `3602.2.2`? That version doesn't seem to be supported

**Comment by docbyte86** [comment] 2024-01-23 06:36
Hello @hcsa73 ,

appreciate your support here. It works! What are the possible values here? Is it possible to use a dynamic value like "latest" ?

**Comment by docbyte86** [comment] 2024-01-23 09:20
If I have a look at the SchwarzIT/stackit provider the value is optional. Maybe that's the solution:

https://registry.terraform.io/providers/SchwarzIT/stackit/latest/docs/resources/kubernetes_cluster

**Comment by hcsa73** [comment] 2024-01-23 11:32
Glad to know I was able to help!

Yes, it's an optional field
We'll further check if it makes sense to implement a dynamic value, or even if this could be a field that TF sets automatically

Closing this as the issue is solved

**Closed by hcsa73** 2024-01-23 11:32 UTC
Labels: bug

**Comment by docbyte86** [comment] 2024-01-23 12:20
@hcsa73 , just to avoid any misunderstanding. According to your provider the field is required:

https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs/resources/ske_cluster

but in the other provider it is optional. Can you verify that please?

**Comment by hcsa73** [comment] 2024-01-23 18:25
Yes, I was mistaken. The field `os_version` in `node_pools` is required, and it must be set to an available OS version. I apologize for the mistake.
Currently there is no way of setting a nodepool's version to be the latest one. We'll look into it how to set this, especially since you can set the cluster's nodepools to auto-update with the field `maintenance.enable_machine_image_version_updates`
