### ISSUE TITLE
No validation for `stackit_ske_cluster.node_pools`

### ISSUE THREAD

**Issue by PeterStolz** [stackitcloud/terraform-provider-stackit#318] opened 2024-04-04 07:01 UTC
Hi,
you can specify arbitrary attributes inside a node_pool definition:

```hcl
 node_pools = [
    {
      name               = "np-example"
      machine_type       = "b1.4"
      os_version         = "3760.2.0"
      minimum            = "1"
      maximum            = "1"
      availability_zones = ["eu01-3"]
      arbitrary = "attribute" # invalid
      volume_size_gb = 300 # invalid
      volume_type = "storage_premium_perf4"
    }
  ]
  ```
  
 This caused quite a bug hunt for me until I saw the missconfiguraiton, as this causes no error. Going forward it will save a lot of people time if we implement proper validation here.

**Comment by vicentepinto98** [comment] 2024-04-04 16:15
Hello @PeterStolz, this is a known issue from terraform and unfortunately it is not something that we can fix on the provider. 

There are open issues raised to terraform regarding this, check https://github.com/hashicorp/terraform-plugin-framework/issues/805 and https://github.com/hashicorp/terraform/issues/33570

You can consider commenting on those issues to raise the priority to get it fixed in terraform.

**Closed by vicentepinto98** 2024-04-04 16:15 UTC

**Comment by PeterStolz** [comment] 2024-04-04 16:41
I do not know how providers work in detail, but at some point you need to make an API request to STACKIT to create the cluster or check its state. Can you not validate it there?
I know that it would be a runtime error now and won't surface in a plan, but in my opinion this workaround is definitely worth it for the enduser.

**Comment by vicentepinto98** [comment] 2024-04-05 08:31
The problem is that the provider doesn't get those invalid attributes at all. Terraform doesn't parse them so we have no way of checking. 

Again, because this is general Terraform behavior, it also doesn't make sense to document this issue in the provider, in my opinion. The users can and should always refer to the resources documentation for the supported attributes.
